baseURL = 'https://jameskelly-uk.github.io'
languageCode = 'en-us'
title = 'James Kelly'
theme = 'jk'
paginate = 5

[taxonomies]
    tag = 'tags'
    category = 'categories'
    series = 'series'

[menu]
[[menu.main]]
    name = 'About'
    url = '/about'
    weight = 10
[[menu.main]]
    name = 'Blog'
    url = '/'
    weight = 20
    pre = ' &#x2022 '
[[menu.main]]
    name = 'Series'
    url = '/series'
    weight = 30
    pre = ' &#x2022 '
[[menu.footer]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/james-kelly-27064332/'
    weight = 10
[[menu.footer]]
    name = 'GitHub'
    url = 'https://github.com/JamesKelly-UK'
    pre = '&#x2022'
    weight = 20