baseURL = 'https://jameskelly-uk.github.io'
languageCode = 'en-us'
title = 'JamesKelly'
theme = 'jk'

[menu]
[[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
[[menu.main]]
    name = 'About'
    url = '/about'
    weight = 15
    pre = ' &#x2022 '
# [[menu.main]]
#     name = 'Projects'
#     url = '/projects'
#     weight = 20
#     pre = ' &#x2022 '


[[menu.footer]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/james-kelly-27064332/'
    weight = 10
[[menu.footer]]
    name = 'GitHub'
    url = 'https://github.com/JamesKelly-UK'
    pre = '&#x2022'
    weight = 20
# [[menu.footer]]
#     name = 'Mastodon'
#     url = '#'
#     pre = '&#x2022'
#     weight = 30    